fakestoreapi_transformation:
  target: target_fakestoreapi-transformation
  outputs:
    target_fakestoreapi-transformation:
      type: snowflake
      # Account instance
      account: "{{ env_var('ACCOUNT') }}"
      # User/password auth
      user: "{{ env_var('USER') }}"
      password: "{{ env_var('PASSWORD') }}"
      # Other authentication configuration
      role: "{{ env_var('ROLE') }}"
      database: "{{ env_var('DATABASE') }}"
      warehouse: "{{ env_var('WAREHOUSE') }}"
      schema: "{{ env_var('SCHEMA') }}"
      threads: 8
